# Generated by Django 5.1.5 on 2025-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('availability', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_information', models.TextField(blank=True, null=True)),
                ('current_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment_provided', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('insurance_coverage', models.TextField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_services', models.TextField(blank=True, null=True)),
                ('rating_avg', models.FloatField(blank=True, null=True)),
                ('response_time', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('service_area', models.TextField(blank=True, null=True)),
                ('social_media', models.TextField(blank=True, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('lat_long', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
