# Generated by Django 5.1.5 on 2025-01-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinformation',
            name='abn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='business_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='lat_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='license_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='rating_avg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessinformation',
            name='trade_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
